=== jboss/xerces/src/test/java/org/apache/xerces/test/secureprocessing/test.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:element name="foo">
      <xs:complexType >
         <xs:sequence minOccurs="0" maxOccurs="10000">
            <xs:element name="bar" type="xs:string"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

</xs:schema>

=== jboss/xerces/src/test/java/org/apache/xerces/test/secureprocessing/foo.xml
<foo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test.xsd">  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar>  <bar>xx</bar></foo>
